#ifndef __CONFIG_H__
#define __CONFIG_H__

#define EEPROM_MODE_PAGE 0
#define EEPROM_MODE_ADDRESS 1

#define EEPROM_MANUAL_MODE_MIN_PAGE 0
#define EEPROM_MANUAL_MODE_MIN_ADDRESS 2

#define EEPROM_MANUAL_MODE_MAX_PAGE 0
#define EEPROM_MANUAL_MODE_MAX_ADDRESS 3

#define EEPROM_AUTO_MODE_MIN_PAGE 1
#define EEPROM_AUTO_MODE_MAX_PAGE 2

#define TIME_REFRESH_DELAY 1000000 //1 s
#define TEMP_REFRESH_DELAY 100000 //100 ms

#define MIN_TEMP 15
#define MAX_TEMP 99

#define BLINK_TIME 250000

#define DEFAULT_MIN_TEMP 35
#define DEFAULT_MAX_TEMP 40

#endif //__CONFIG_H__